### ISSUE TITLE
Non-integer charges

### ISSUE THREAD

**Issue by aniketsh** [openforcefield/openff-forcefields#34]
Hi,

I am getting some non-integer charges with am1bcc, for instance 0.003. Is there any fix for this already implemented? 

OS: MacOS
OFF version: 1.3

**Comment by j-wags** [comment]
Hi @aniketsh,

Thanks for the report. We've seen this problem before, but we don't have a solution implemented. I had suggested a few options in https://github.com/openforcefield/openff-toolkit/issues/456 but didn't get much feedback at the time. 

If this is indeed what you're asking about, would you be willing to close this issue and move this discussion over there? 

This shouldn't be too hard once we settle on a desired API for the rounding. Basically, we probably want option 1 on that issue (apply equal offsets to all atoms by default to ensure that the partial charges sum to the total formal charge, but let the user provide a manual override if they DON'T want rounding to be applied).

**Comment by aniketsh** [comment]
@j-wags 
Sure, will do that.
